package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfExecutionTaskOutput;
import com.yatop.lambda.base.model.WfExecutionTaskOutputExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfExecutionTaskOutputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Jan 20 20:16:57 CST 2019
     */
    long countByExample(WfExecutionTaskOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Jan 20 20:16:57 CST 2019
     */
    int deleteByExample(WfExecutionTaskOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Jan 20 20:16:57 CST 2019
     */
    int insert(WfExecutionTaskOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Jan 20 20:16:57 CST 2019
     */
    int insertSelective(WfExecutionTaskOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Jan 20 20:16:57 CST 2019
     */
    List<WfExecutionTaskOutput> selectByExample(WfExecutionTaskOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Jan 20 20:16:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfExecutionTaskOutput record, @Param("example") WfExecutionTaskOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Jan 20 20:16:57 CST 2019
     */
    int updateByExample(@Param("record") WfExecutionTaskOutput record, @Param("example") WfExecutionTaskOutputExample example);
}