package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfExecutionQueue;
import com.yatop.lambda.base.model.WfExecutionQueueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfExecutionQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    long countByExample(WfExecutionQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int deleteByExample(WfExecutionQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int deleteByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int insert(WfExecutionQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int insertSelective(WfExecutionQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    List<WfExecutionQueue> selectByExample(WfExecutionQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    WfExecutionQueue selectByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfExecutionQueue record, @Param("example") WfExecutionQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int updateByExample(@Param("record") WfExecutionQueue record, @Param("example") WfExecutionQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int updateByPrimaryKeySelective(WfExecutionQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_queue
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int updateByPrimaryKey(WfExecutionQueue record);
}