package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfUserFavoriteModule;
import com.yatop.lambda.base.model.WfUserFavoriteModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfUserFavoriteModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_user_favorite_module
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    long countByExample(WfUserFavoriteModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_user_favorite_module
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int deleteByExample(WfUserFavoriteModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_user_favorite_module
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int insert(WfUserFavoriteModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_user_favorite_module
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int insertSelective(WfUserFavoriteModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_user_favorite_module
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    List<WfUserFavoriteModule> selectByExample(WfUserFavoriteModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_user_favorite_module
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfUserFavoriteModule record, @Param("example") WfUserFavoriteModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_user_favorite_module
     *
     * @mbg.generated Wed Jan 02 16:24:07 CST 2019
     */
    int updateByExample(@Param("record") WfUserFavoriteModule record, @Param("example") WfUserFavoriteModuleExample example);
}