package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;

public class CfCmptAlgorithm extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_ID
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private Long algorithmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_ID:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean algorithmIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_CODE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private String algorithmCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_CODE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean algorithmCodeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_NAME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private String algorithmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_NAME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean algorithmNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_TYPE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private Integer algorithmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean algorithmTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_LABELS
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private String algorithmLabels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.ALGORITHM_LABELS:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean algorithmLabelsColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.LEARNING_MODE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private Integer learningMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.LEARNING_MODE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean learningModeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.IS_TUNABLE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private Integer isTunable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.IS_TUNABLE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean isTunableColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.DESCRIPTION
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.DESCRIPTION:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.STATUS
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.STATUS:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.LAST_UPDATE_TIME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.LAST_UPDATE_OPER
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.CREATE_TIME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.CREATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.CREATE_OPER
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_algorithm.CREATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private boolean createOperColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cf_cmpt_algorithm
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_ID
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_ID
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public Long getAlgorithmId() {
        return algorithmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_ID:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_ID:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmIdColoured() {
        return algorithmIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_ID:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_ID:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmIdNotColoured() {
        return !algorithmIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_ID
     *
     * @param algorithmId the value for cf_cmpt_algorithm.ALGORITHM_ID
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmId(Long algorithmId) {
        this.algorithmId = algorithmId;
        this.algorithmIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_ID:Coloured
     *
     * @param algorithmIdColoured the value for cf_cmpt_algorithm.ALGORITHM_ID:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmIdColoured(boolean algorithmIdColoured) {
        this.algorithmIdColoured = algorithmIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_CODE
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_CODE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public String getAlgorithmCode() {
        return algorithmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_CODE:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_CODE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmCodeColoured() {
        return algorithmCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_CODE:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_CODE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmCodeNotColoured() {
        return !algorithmCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_CODE
     *
     * @param algorithmCode the value for cf_cmpt_algorithm.ALGORITHM_CODE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmCode(String algorithmCode) {
        this.algorithmCode = algorithmCode == null ? null : algorithmCode.trim();
        this.algorithmCodeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_CODE:Coloured
     *
     * @param algorithmCodeColoured the value for cf_cmpt_algorithm.ALGORITHM_CODE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmCodeColoured(boolean algorithmCodeColoured) {
        this.algorithmCodeColoured = algorithmCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_NAME
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_NAME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public String getAlgorithmName() {
        return algorithmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_NAME:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_NAME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmNameColoured() {
        return algorithmNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_NAME:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_NAME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmNameNotColoured() {
        return !algorithmNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_NAME
     *
     * @param algorithmName the value for cf_cmpt_algorithm.ALGORITHM_NAME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmName(String algorithmName) {
        this.algorithmName = algorithmName == null ? null : algorithmName.trim();
        this.algorithmNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_NAME:Coloured
     *
     * @param algorithmNameColoured the value for cf_cmpt_algorithm.ALGORITHM_NAME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmNameColoured(boolean algorithmNameColoured) {
        this.algorithmNameColoured = algorithmNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_TYPE
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_TYPE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public Integer getAlgorithmType() {
        return algorithmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_TYPE:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmTypeColoured() {
        return algorithmTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_TYPE:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmTypeNotColoured() {
        return !algorithmTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_TYPE
     *
     * @param algorithmType the value for cf_cmpt_algorithm.ALGORITHM_TYPE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmType(Integer algorithmType) {
        this.algorithmType = algorithmType;
        this.algorithmTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_TYPE:Coloured
     *
     * @param algorithmTypeColoured the value for cf_cmpt_algorithm.ALGORITHM_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmTypeColoured(boolean algorithmTypeColoured) {
        this.algorithmTypeColoured = algorithmTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_LABELS
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_LABELS
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public String getAlgorithmLabels() {
        return algorithmLabels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_LABELS:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_LABELS:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmLabelsColoured() {
        return algorithmLabelsColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.ALGORITHM_LABELS:Coloured
     *
     * @return the value of cf_cmpt_algorithm.ALGORITHM_LABELS:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isAlgorithmLabelsNotColoured() {
        return !algorithmLabelsColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_LABELS
     *
     * @param algorithmLabels the value for cf_cmpt_algorithm.ALGORITHM_LABELS
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmLabels(String algorithmLabels) {
        this.algorithmLabels = algorithmLabels == null ? null : algorithmLabels.trim();
        this.algorithmLabelsColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.ALGORITHM_LABELS:Coloured
     *
     * @param algorithmLabelsColoured the value for cf_cmpt_algorithm.ALGORITHM_LABELS:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setAlgorithmLabelsColoured(boolean algorithmLabelsColoured) {
        this.algorithmLabelsColoured = algorithmLabelsColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LEARNING_MODE
     *
     * @return the value of cf_cmpt_algorithm.LEARNING_MODE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public Integer getLearningMode() {
        return learningMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LEARNING_MODE:Coloured
     *
     * @return the value of cf_cmpt_algorithm.LEARNING_MODE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isLearningModeColoured() {
        return learningModeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LEARNING_MODE:Coloured
     *
     * @return the value of cf_cmpt_algorithm.LEARNING_MODE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isLearningModeNotColoured() {
        return !learningModeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.LEARNING_MODE
     *
     * @param learningMode the value for cf_cmpt_algorithm.LEARNING_MODE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setLearningMode(Integer learningMode) {
        this.learningMode = learningMode;
        this.learningModeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.LEARNING_MODE:Coloured
     *
     * @param learningModeColoured the value for cf_cmpt_algorithm.LEARNING_MODE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setLearningModeColoured(boolean learningModeColoured) {
        this.learningModeColoured = learningModeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.IS_TUNABLE
     *
     * @return the value of cf_cmpt_algorithm.IS_TUNABLE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public Integer getIsTunable() {
        return isTunable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.IS_TUNABLE:Coloured
     *
     * @return the value of cf_cmpt_algorithm.IS_TUNABLE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isIsTunableColoured() {
        return isTunableColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.IS_TUNABLE:Coloured
     *
     * @return the value of cf_cmpt_algorithm.IS_TUNABLE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isIsTunableNotColoured() {
        return !isTunableColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.IS_TUNABLE
     *
     * @param isTunable the value for cf_cmpt_algorithm.IS_TUNABLE
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setIsTunable(Integer isTunable) {
        this.isTunable = isTunable;
        this.isTunableColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.IS_TUNABLE:Coloured
     *
     * @param isTunableColoured the value for cf_cmpt_algorithm.IS_TUNABLE:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setIsTunableColoured(boolean isTunableColoured) {
        this.isTunableColoured = isTunableColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.DESCRIPTION
     *
     * @return the value of cf_cmpt_algorithm.DESCRIPTION
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.DESCRIPTION:Coloured
     *
     * @return the value of cf_cmpt_algorithm.DESCRIPTION:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.DESCRIPTION:Coloured
     *
     * @return the value of cf_cmpt_algorithm.DESCRIPTION:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isDescriptionNotColoured() {
        return !descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.DESCRIPTION
     *
     * @param description the value for cf_cmpt_algorithm.DESCRIPTION
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for cf_cmpt_algorithm.DESCRIPTION:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.STATUS
     *
     * @return the value of cf_cmpt_algorithm.STATUS
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.STATUS:Coloured
     *
     * @return the value of cf_cmpt_algorithm.STATUS:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.STATUS:Coloured
     *
     * @return the value of cf_cmpt_algorithm.STATUS:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isStatusNotColoured() {
        return !statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.STATUS
     *
     * @param status the value for cf_cmpt_algorithm.STATUS
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.STATUS:Coloured
     *
     * @param statusColoured the value for cf_cmpt_algorithm.STATUS:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LAST_UPDATE_TIME
     *
     * @return the value of cf_cmpt_algorithm.LAST_UPDATE_TIME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of cf_cmpt_algorithm.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of cf_cmpt_algorithm.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isLastUpdateTimeNotColoured() {
        return !lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for cf_cmpt_algorithm.LAST_UPDATE_TIME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for cf_cmpt_algorithm.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LAST_UPDATE_OPER
     *
     * @return the value of cf_cmpt_algorithm.LAST_UPDATE_OPER
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of cf_cmpt_algorithm.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of cf_cmpt_algorithm.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isLastUpdateOperNotColoured() {
        return !lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for cf_cmpt_algorithm.LAST_UPDATE_OPER
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for cf_cmpt_algorithm.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.CREATE_TIME
     *
     * @return the value of cf_cmpt_algorithm.CREATE_TIME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.CREATE_TIME:Coloured
     *
     * @return the value of cf_cmpt_algorithm.CREATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.CREATE_TIME:Coloured
     *
     * @return the value of cf_cmpt_algorithm.CREATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isCreateTimeNotColoured() {
        return !createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.CREATE_TIME
     *
     * @param createTime the value for cf_cmpt_algorithm.CREATE_TIME
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for cf_cmpt_algorithm.CREATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.CREATE_OPER
     *
     * @return the value of cf_cmpt_algorithm.CREATE_OPER
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.CREATE_OPER:Coloured
     *
     * @return the value of cf_cmpt_algorithm.CREATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_algorithm.CREATE_OPER:Coloured
     *
     * @return the value of cf_cmpt_algorithm.CREATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public boolean isCreateOperNotColoured() {
        return !createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.CREATE_OPER
     *
     * @param createOper the value for cf_cmpt_algorithm.CREATE_OPER
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_algorithm.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for cf_cmpt_algorithm.CREATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_algorithm
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CfCmptAlgorithm other = (CfCmptAlgorithm) that;
        return (this.getAlgorithmId() == null ? other.getAlgorithmId() == null : this.getAlgorithmId().equals(other.getAlgorithmId()))
            && (this.getAlgorithmCode() == null ? other.getAlgorithmCode() == null : this.getAlgorithmCode().equals(other.getAlgorithmCode()))
            && (this.getAlgorithmName() == null ? other.getAlgorithmName() == null : this.getAlgorithmName().equals(other.getAlgorithmName()))
            && (this.getAlgorithmType() == null ? other.getAlgorithmType() == null : this.getAlgorithmType().equals(other.getAlgorithmType()))
            && (this.getAlgorithmLabels() == null ? other.getAlgorithmLabels() == null : this.getAlgorithmLabels().equals(other.getAlgorithmLabels()))
            && (this.getLearningMode() == null ? other.getLearningMode() == null : this.getLearningMode().equals(other.getLearningMode()))
            && (this.getIsTunable() == null ? other.getIsTunable() == null : this.getIsTunable().equals(other.getIsTunable()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_algorithm
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAlgorithmId() == null) ? 0 : getAlgorithmId().hashCode());
        result = prime * result + ((getAlgorithmCode() == null) ? 0 : getAlgorithmCode().hashCode());
        result = prime * result + ((getAlgorithmName() == null) ? 0 : getAlgorithmName().hashCode());
        result = prime * result + ((getAlgorithmType() == null) ? 0 : getAlgorithmType().hashCode());
        result = prime * result + ((getAlgorithmLabels() == null) ? 0 : getAlgorithmLabels().hashCode());
        result = prime * result + ((getLearningMode() == null) ? 0 : getLearningMode().hashCode());
        result = prime * result + ((getIsTunable() == null) ? 0 : getIsTunable().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_algorithm
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    public void copyProperties(CfCmptAlgorithm that) {
        if (this == that || that == null) {
            return;
        }
        if(that.isAlgorithmIdColoured() ) {this.setAlgorithmId(that.getAlgorithmId() );}
        if(that.isAlgorithmCodeColoured() ) {this.setAlgorithmCode(that.getAlgorithmCode() );}
        if(that.isAlgorithmNameColoured() ) {this.setAlgorithmName(that.getAlgorithmName() );}
        if(that.isAlgorithmTypeColoured() ) {this.setAlgorithmType(that.getAlgorithmType() );}
        if(that.isAlgorithmLabelsColoured() ) {this.setAlgorithmLabels(that.getAlgorithmLabels() );}
        if(that.isLearningModeColoured() ) {this.setLearningMode(that.getLearningMode() );}
        if(that.isIsTunableColoured() ) {this.setIsTunable(that.getIsTunable() );}
        if(that.isDescriptionColoured() ) {this.setDescription(that.getDescription() );}
        if(that.isStatusColoured() ) {this.setStatus(that.getStatus() );}
        if(that.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(that.getLastUpdateTime() );}
        if(that.isLastUpdateOperColoured() ) {this.setLastUpdateOper(that.getLastUpdateOper() );}
        if(that.isCreateTimeColoured() ) {this.setCreateTime(that.getCreateTime() );}
        if(that.isCreateOperColoured() ) {this.setCreateOper(that.getCreateOper() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_algorithm
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        JSONObject jsonObj = new JSONObject(32, true);
        if(this.algorithmIdColoured) {jsonObj.put("algorithmId", this.algorithmId);}
        if(this.algorithmCodeColoured) {jsonObj.put("algorithmCode", this.algorithmCode);}
        if(this.algorithmNameColoured) {jsonObj.put("algorithmName", this.algorithmName);}
        if(this.algorithmTypeColoured) {jsonObj.put("algorithmType", this.algorithmType);}
        if(this.algorithmLabelsColoured) {jsonObj.put("algorithmLabels", this.algorithmLabels);}
        if(this.learningModeColoured) {jsonObj.put("learningMode", this.learningMode);}
        if(this.isTunableColoured) {jsonObj.put("isTunable", this.isTunable);}
        if(this.descriptionColoured) {jsonObj.put("description", this.description);}
        if(this.statusColoured) {jsonObj.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {jsonObj.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {jsonObj.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {jsonObj.put("createTime", this.createTime);}
        if(this.createOperColoured) {jsonObj.put("createOper", this.createOper);}
        return jsonObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_algorithm
     *
     * @mbg.generated Mon Dec 17 01:50:09 CST 2018
     */
    @Override
    public void clear() {
         this.algorithmId = null; this.algorithmIdColoured = false;
         this.algorithmCode = null; this.algorithmCodeColoured = false;
         this.algorithmName = null; this.algorithmNameColoured = false;
         this.algorithmType = null; this.algorithmTypeColoured = false;
         this.algorithmLabels = null; this.algorithmLabelsColoured = false;
         this.learningMode = null; this.learningModeColoured = false;
         this.isTunable = null; this.isTunableColoured = false;
         this.description = null; this.descriptionColoured = false;
         this.status = null; this.statusColoured = false;
         this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;
         this.lastUpdateOper = null; this.lastUpdateOperColoured = false;
         this.createTime = null; this.createTimeColoured = false;
         this.createOper = null; this.createOperColoured = false;
        return;
    }
}