package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;

public class EmExperimentTemplate extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.TEMPLATE_ID
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private Long templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.TEMPLATE_ID:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean templateIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.TEMPLATE_NAME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.TEMPLATE_NAME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean templateNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.SEQUENCE
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.SEQUENCE:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean sequenceColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.TEMPLATE_COUNT
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private Long templateCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.TEMPLATE_COUNT:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean templateCountColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.SUMMARY
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.SUMMARY:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean summaryColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.DESCRIPTION
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.STATUS
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.STATUS:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.CREATE_TIME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.CREATE_OPER
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean createOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.TEMPLATE_CONTENT
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private String templateContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_experiment_template.TEMPLATE_CONTENT:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private boolean templateContentColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table em_experiment_template
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_ID
     *
     * @return the value of em_experiment_template.TEMPLATE_ID
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_ID:Coloured
     *
     * @return the value of em_experiment_template.TEMPLATE_ID:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isTemplateIdColoured() {
        return templateIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_ID:Coloured
     *
     * @return the value of em_experiment_template.TEMPLATE_ID:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isTemplateIdNotColoured() {
        return !templateIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.TEMPLATE_ID
     *
     * @param templateId the value for em_experiment_template.TEMPLATE_ID
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
        this.templateIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.TEMPLATE_ID:Coloured
     *
     * @param templateIdColoured the value for em_experiment_template.TEMPLATE_ID:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setTemplateIdColoured(boolean templateIdColoured) {
        this.templateIdColoured = templateIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_NAME
     *
     * @return the value of em_experiment_template.TEMPLATE_NAME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_NAME:Coloured
     *
     * @return the value of em_experiment_template.TEMPLATE_NAME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isTemplateNameColoured() {
        return templateNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_NAME:Coloured
     *
     * @return the value of em_experiment_template.TEMPLATE_NAME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isTemplateNameNotColoured() {
        return !templateNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.TEMPLATE_NAME
     *
     * @param templateName the value for em_experiment_template.TEMPLATE_NAME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
        this.templateNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.TEMPLATE_NAME:Coloured
     *
     * @param templateNameColoured the value for em_experiment_template.TEMPLATE_NAME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setTemplateNameColoured(boolean templateNameColoured) {
        this.templateNameColoured = templateNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.SEQUENCE
     *
     * @return the value of em_experiment_template.SEQUENCE
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.SEQUENCE:Coloured
     *
     * @return the value of em_experiment_template.SEQUENCE:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isSequenceColoured() {
        return sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.SEQUENCE:Coloured
     *
     * @return the value of em_experiment_template.SEQUENCE:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isSequenceNotColoured() {
        return !sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.SEQUENCE
     *
     * @param sequence the value for em_experiment_template.SEQUENCE
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
        this.sequenceColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.SEQUENCE:Coloured
     *
     * @param sequenceColoured the value for em_experiment_template.SEQUENCE:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setSequenceColoured(boolean sequenceColoured) {
        this.sequenceColoured = sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_COUNT
     *
     * @return the value of em_experiment_template.TEMPLATE_COUNT
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public Long getTemplateCount() {
        return templateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_COUNT:Coloured
     *
     * @return the value of em_experiment_template.TEMPLATE_COUNT:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isTemplateCountColoured() {
        return templateCountColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_COUNT:Coloured
     *
     * @return the value of em_experiment_template.TEMPLATE_COUNT:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isTemplateCountNotColoured() {
        return !templateCountColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.TEMPLATE_COUNT
     *
     * @param templateCount the value for em_experiment_template.TEMPLATE_COUNT
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setTemplateCount(Long templateCount) {
        this.templateCount = templateCount;
        this.templateCountColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.TEMPLATE_COUNT:Coloured
     *
     * @param templateCountColoured the value for em_experiment_template.TEMPLATE_COUNT:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setTemplateCountColoured(boolean templateCountColoured) {
        this.templateCountColoured = templateCountColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.SUMMARY
     *
     * @return the value of em_experiment_template.SUMMARY
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.SUMMARY:Coloured
     *
     * @return the value of em_experiment_template.SUMMARY:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isSummaryColoured() {
        return summaryColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.SUMMARY:Coloured
     *
     * @return the value of em_experiment_template.SUMMARY:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isSummaryNotColoured() {
        return !summaryColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.SUMMARY
     *
     * @param summary the value for em_experiment_template.SUMMARY
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
        this.summaryColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.SUMMARY:Coloured
     *
     * @param summaryColoured the value for em_experiment_template.SUMMARY:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setSummaryColoured(boolean summaryColoured) {
        this.summaryColoured = summaryColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.DESCRIPTION
     *
     * @return the value of em_experiment_template.DESCRIPTION
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.DESCRIPTION:Coloured
     *
     * @return the value of em_experiment_template.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.DESCRIPTION:Coloured
     *
     * @return the value of em_experiment_template.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isDescriptionNotColoured() {
        return !descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.DESCRIPTION
     *
     * @param description the value for em_experiment_template.DESCRIPTION
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for em_experiment_template.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.STATUS
     *
     * @return the value of em_experiment_template.STATUS
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.STATUS:Coloured
     *
     * @return the value of em_experiment_template.STATUS:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.STATUS:Coloured
     *
     * @return the value of em_experiment_template.STATUS:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isStatusNotColoured() {
        return !statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.STATUS
     *
     * @param status the value for em_experiment_template.STATUS
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.STATUS:Coloured
     *
     * @param statusColoured the value for em_experiment_template.STATUS:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.LAST_UPDATE_TIME
     *
     * @return the value of em_experiment_template.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of em_experiment_template.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of em_experiment_template.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isLastUpdateTimeNotColoured() {
        return !lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for em_experiment_template.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for em_experiment_template.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.LAST_UPDATE_OPER
     *
     * @return the value of em_experiment_template.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of em_experiment_template.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of em_experiment_template.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isLastUpdateOperNotColoured() {
        return !lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for em_experiment_template.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for em_experiment_template.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.CREATE_TIME
     *
     * @return the value of em_experiment_template.CREATE_TIME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.CREATE_TIME:Coloured
     *
     * @return the value of em_experiment_template.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.CREATE_TIME:Coloured
     *
     * @return the value of em_experiment_template.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isCreateTimeNotColoured() {
        return !createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.CREATE_TIME
     *
     * @param createTime the value for em_experiment_template.CREATE_TIME
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for em_experiment_template.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.CREATE_OPER
     *
     * @return the value of em_experiment_template.CREATE_OPER
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.CREATE_OPER:Coloured
     *
     * @return the value of em_experiment_template.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.CREATE_OPER:Coloured
     *
     * @return the value of em_experiment_template.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isCreateOperNotColoured() {
        return !createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.CREATE_OPER
     *
     * @param createOper the value for em_experiment_template.CREATE_OPER
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for em_experiment_template.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_CONTENT
     *
     * @return the value of em_experiment_template.TEMPLATE_CONTENT
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_CONTENT:Coloured
     *
     * @return the value of em_experiment_template.TEMPLATE_CONTENT:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isTemplateContentColoured() {
        return templateContentColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_experiment_template.TEMPLATE_CONTENT:Coloured
     *
     * @return the value of em_experiment_template.TEMPLATE_CONTENT:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public boolean isTemplateContentNotColoured() {
        return !templateContentColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.TEMPLATE_CONTENT
     *
     * @param templateContent the value for em_experiment_template.TEMPLATE_CONTENT
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent == null ? null : templateContent.trim();
        this.templateContentColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_experiment_template.TEMPLATE_CONTENT:Coloured
     *
     * @param templateContentColoured the value for em_experiment_template.TEMPLATE_CONTENT:Coloured
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void setTemplateContentColoured(boolean templateContentColoured) {
        this.templateContentColoured = templateContentColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_experiment_template
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if(!(that instanceof EmExperimentTemplate)) {
            return false;
        }
        EmExperimentTemplate other = (EmExperimentTemplate) that;
        return (this.getTemplateId() == null ? other.getTemplateId() == null : this.getTemplateId().equals(other.getTemplateId()))
            && (this.getTemplateName() == null ? other.getTemplateName() == null : this.getTemplateName().equals(other.getTemplateName()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getTemplateCount() == null ? other.getTemplateCount() == null : this.getTemplateCount().equals(other.getTemplateCount()))
            && (this.getSummary() == null ? other.getSummary() == null : this.getSummary().equals(other.getSummary()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()))
            && (this.getTemplateContent() == null ? other.getTemplateContent() == null : this.getTemplateContent().equals(other.getTemplateContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_experiment_template
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTemplateId() == null) ? 0 : getTemplateId().hashCode());
        result = prime * result + ((getTemplateName() == null) ? 0 : getTemplateName().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getTemplateCount() == null) ? 0 : getTemplateCount().hashCode());
        result = prime * result + ((getSummary() == null) ? 0 : getSummary().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        result = prime * result + ((getTemplateContent() == null) ? 0 : getTemplateContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_experiment_template
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    public void copyProperties(EmExperimentTemplate that) {
        if (this == that || that == null) {
            return;
        }
        if(that.isTemplateIdColoured() ) {this.setTemplateId(that.getTemplateId() );}
        if(that.isTemplateNameColoured() ) {this.setTemplateName(that.getTemplateName() );}
        if(that.isSequenceColoured() ) {this.setSequence(that.getSequence() );}
        if(that.isTemplateCountColoured() ) {this.setTemplateCount(that.getTemplateCount() );}
        if(that.isSummaryColoured() ) {this.setSummary(that.getSummary() );}
        if(that.isDescriptionColoured() ) {this.setDescription(that.getDescription() );}
        if(that.isStatusColoured() ) {this.setStatus(that.getStatus() );}
        if(that.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(that.getLastUpdateTime() );}
        if(that.isLastUpdateOperColoured() ) {this.setLastUpdateOper(that.getLastUpdateOper() );}
        if(that.isCreateTimeColoured() ) {this.setCreateTime(that.getCreateTime() );}
        if(that.isCreateOperColoured() ) {this.setCreateOper(that.getCreateOper() );}
        if(that.isTemplateContentColoured() ) {this.setTemplateContent(that.getTemplateContent() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_experiment_template
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    @Override
    public JSONObject toJSON() {
        JSONObject jsonObj = new JSONObject(32, true);
        if(this.templateId != null) {jsonObj.put("templateId", this.templateId);}
        if(this.templateName != null) {jsonObj.put("templateName", this.templateName);}
        if(this.sequence != null) {jsonObj.put("sequence", this.sequence);}
        if(this.templateCount != null) {jsonObj.put("templateCount", this.templateCount);}
        if(this.summary != null) {jsonObj.put("summary", this.summary);}
        if(this.description != null) {jsonObj.put("description", this.description);}
        if(this.status != null) {jsonObj.put("status", this.status);}
        if(this.lastUpdateTime != null) {jsonObj.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOper != null) {jsonObj.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTime != null) {jsonObj.put("createTime", this.createTime);}
        if(this.createOper != null) {jsonObj.put("createOper", this.createOper);}
        if(this.templateContent != null) {jsonObj.put("templateContent", this.templateContent);}
        return jsonObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_experiment_template
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    @Override
    public void clear() {
         this.templateId = null; this.templateIdColoured = false;
         this.templateName = null; this.templateNameColoured = false;
         this.sequence = null; this.sequenceColoured = false;
         this.templateCount = null; this.templateCountColoured = false;
         this.summary = null; this.summaryColoured = false;
         this.description = null; this.descriptionColoured = false;
         this.status = null; this.statusColoured = false;
         this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;
         this.lastUpdateOper = null; this.lastUpdateOperColoured = false;
         this.createTime = null; this.createTimeColoured = false;
         this.createOper = null; this.createOperColoured = false;
         this.templateContent = null; this.templateContentColoured = false;
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_experiment_template
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    @Override
    public void clearColoured() {
        this.templateIdColoured = false;
        this.templateNameColoured = false;
        this.sequenceColoured = false;
        this.templateCountColoured = false;
        this.summaryColoured = false;
        this.descriptionColoured = false;
        this.statusColoured = false;
        this.lastUpdateTimeColoured = false;
        this.lastUpdateOperColoured = false;
        this.createTimeColoured = false;
        this.createOperColoured = false;
        this.templateContentColoured = false;
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_experiment_template
     *
     * @mbg.generated Tue Jan 22 01:22:51 CST 2019
     */
    @Override
    public boolean isColoured() {
        if(this.templateIdColoured) return true;
        if(this.templateNameColoured) return true;
        if(this.sequenceColoured) return true;
        if(this.templateCountColoured) return true;
        if(this.summaryColoured) return true;
        if(this.descriptionColoured) return true;
        if(this.statusColoured) return true;
        if(this.lastUpdateTimeColoured) return true;
        if(this.lastUpdateOperColoured) return true;
        if(this.createTimeColoured) return true;
        if(this.createOperColoured) return true;
        if(this.templateContentColoured) return true;
        return false;
    }
}