package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;

public class MwModelWarehouse extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MW_ID
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private Long mwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MW_ID:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean mwIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MW_CODE
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private String mwCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MW_CODE:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean mwCodeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MW_NAME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private String mwName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MW_NAME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean mwNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MW_TYPE
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private Integer mwType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MW_TYPE:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean mwTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.OWNER_PROJECT_ID
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private Long ownerProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean ownerProjectIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MODEL_DFS_DIR
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private String modelDfsDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MODEL_DFS_DIR:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean modelDfsDirColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MODEL_LOCAL_DIR
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private String modelLocalDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.MODEL_LOCAL_DIR:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean modelLocalDirColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.DESCRIPTION
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.STATUS
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.STATUS:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.CREATE_TIME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.CREATE_OPER
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mw_model_warehouse.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private boolean createOperColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mw_model_warehouse
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_ID
     *
     * @return the value of mw_model_warehouse.MW_ID
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public Long getMwId() {
        return mwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_ID:Coloured
     *
     * @return the value of mw_model_warehouse.MW_ID:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isMwIdColoured() {
        return mwIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_ID:Coloured
     *
     * @return the value of mw_model_warehouse.MW_ID:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isMwIdNotColoured() {
        return !mwIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MW_ID
     *
     * @param mwId the value for mw_model_warehouse.MW_ID
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setMwId(Long mwId) {
        this.mwId = mwId;
        this.mwIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MW_ID:Coloured
     *
     * @param mwIdColoured the value for mw_model_warehouse.MW_ID:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setMwIdColoured(boolean mwIdColoured) {
        this.mwIdColoured = mwIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_CODE
     *
     * @return the value of mw_model_warehouse.MW_CODE
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public String getMwCode() {
        return mwCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_CODE:Coloured
     *
     * @return the value of mw_model_warehouse.MW_CODE:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isMwCodeColoured() {
        return mwCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_CODE:Coloured
     *
     * @return the value of mw_model_warehouse.MW_CODE:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isMwCodeNotColoured() {
        return !mwCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MW_CODE
     *
     * @param mwCode the value for mw_model_warehouse.MW_CODE
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setMwCode(String mwCode) {
        this.mwCode = mwCode == null ? null : mwCode.trim();
        this.mwCodeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MW_CODE:Coloured
     *
     * @param mwCodeColoured the value for mw_model_warehouse.MW_CODE:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setMwCodeColoured(boolean mwCodeColoured) {
        this.mwCodeColoured = mwCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_NAME
     *
     * @return the value of mw_model_warehouse.MW_NAME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public String getMwName() {
        return mwName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_NAME:Coloured
     *
     * @return the value of mw_model_warehouse.MW_NAME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isMwNameColoured() {
        return mwNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_NAME:Coloured
     *
     * @return the value of mw_model_warehouse.MW_NAME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isMwNameNotColoured() {
        return !mwNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MW_NAME
     *
     * @param mwName the value for mw_model_warehouse.MW_NAME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setMwName(String mwName) {
        this.mwName = mwName == null ? null : mwName.trim();
        this.mwNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MW_NAME:Coloured
     *
     * @param mwNameColoured the value for mw_model_warehouse.MW_NAME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setMwNameColoured(boolean mwNameColoured) {
        this.mwNameColoured = mwNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_TYPE
     *
     * @return the value of mw_model_warehouse.MW_TYPE
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public Integer getMwType() {
        return mwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_TYPE:Coloured
     *
     * @return the value of mw_model_warehouse.MW_TYPE:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isMwTypeColoured() {
        return mwTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MW_TYPE:Coloured
     *
     * @return the value of mw_model_warehouse.MW_TYPE:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isMwTypeNotColoured() {
        return !mwTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MW_TYPE
     *
     * @param mwType the value for mw_model_warehouse.MW_TYPE
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setMwType(Integer mwType) {
        this.mwType = mwType;
        this.mwTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MW_TYPE:Coloured
     *
     * @param mwTypeColoured the value for mw_model_warehouse.MW_TYPE:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setMwTypeColoured(boolean mwTypeColoured) {
        this.mwTypeColoured = mwTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.OWNER_PROJECT_ID
     *
     * @return the value of mw_model_warehouse.OWNER_PROJECT_ID
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public Long getOwnerProjectId() {
        return ownerProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.OWNER_PROJECT_ID:Coloured
     *
     * @return the value of mw_model_warehouse.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isOwnerProjectIdColoured() {
        return ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.OWNER_PROJECT_ID:Coloured
     *
     * @return the value of mw_model_warehouse.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isOwnerProjectIdNotColoured() {
        return !ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.OWNER_PROJECT_ID
     *
     * @param ownerProjectId the value for mw_model_warehouse.OWNER_PROJECT_ID
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setOwnerProjectId(Long ownerProjectId) {
        this.ownerProjectId = ownerProjectId;
        this.ownerProjectIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.OWNER_PROJECT_ID:Coloured
     *
     * @param ownerProjectIdColoured the value for mw_model_warehouse.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setOwnerProjectIdColoured(boolean ownerProjectIdColoured) {
        this.ownerProjectIdColoured = ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MODEL_DFS_DIR
     *
     * @return the value of mw_model_warehouse.MODEL_DFS_DIR
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public String getModelDfsDir() {
        return modelDfsDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MODEL_DFS_DIR:Coloured
     *
     * @return the value of mw_model_warehouse.MODEL_DFS_DIR:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isModelDfsDirColoured() {
        return modelDfsDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MODEL_DFS_DIR:Coloured
     *
     * @return the value of mw_model_warehouse.MODEL_DFS_DIR:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isModelDfsDirNotColoured() {
        return !modelDfsDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MODEL_DFS_DIR
     *
     * @param modelDfsDir the value for mw_model_warehouse.MODEL_DFS_DIR
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setModelDfsDir(String modelDfsDir) {
        this.modelDfsDir = modelDfsDir == null ? null : modelDfsDir.trim();
        this.modelDfsDirColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MODEL_DFS_DIR:Coloured
     *
     * @param modelDfsDirColoured the value for mw_model_warehouse.MODEL_DFS_DIR:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setModelDfsDirColoured(boolean modelDfsDirColoured) {
        this.modelDfsDirColoured = modelDfsDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MODEL_LOCAL_DIR
     *
     * @return the value of mw_model_warehouse.MODEL_LOCAL_DIR
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public String getModelLocalDir() {
        return modelLocalDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MODEL_LOCAL_DIR:Coloured
     *
     * @return the value of mw_model_warehouse.MODEL_LOCAL_DIR:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isModelLocalDirColoured() {
        return modelLocalDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.MODEL_LOCAL_DIR:Coloured
     *
     * @return the value of mw_model_warehouse.MODEL_LOCAL_DIR:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isModelLocalDirNotColoured() {
        return !modelLocalDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MODEL_LOCAL_DIR
     *
     * @param modelLocalDir the value for mw_model_warehouse.MODEL_LOCAL_DIR
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setModelLocalDir(String modelLocalDir) {
        this.modelLocalDir = modelLocalDir == null ? null : modelLocalDir.trim();
        this.modelLocalDirColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.MODEL_LOCAL_DIR:Coloured
     *
     * @param modelLocalDirColoured the value for mw_model_warehouse.MODEL_LOCAL_DIR:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setModelLocalDirColoured(boolean modelLocalDirColoured) {
        this.modelLocalDirColoured = modelLocalDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.DESCRIPTION
     *
     * @return the value of mw_model_warehouse.DESCRIPTION
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.DESCRIPTION:Coloured
     *
     * @return the value of mw_model_warehouse.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.DESCRIPTION:Coloured
     *
     * @return the value of mw_model_warehouse.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isDescriptionNotColoured() {
        return !descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.DESCRIPTION
     *
     * @param description the value for mw_model_warehouse.DESCRIPTION
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for mw_model_warehouse.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.STATUS
     *
     * @return the value of mw_model_warehouse.STATUS
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.STATUS:Coloured
     *
     * @return the value of mw_model_warehouse.STATUS:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.STATUS:Coloured
     *
     * @return the value of mw_model_warehouse.STATUS:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isStatusNotColoured() {
        return !statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.STATUS
     *
     * @param status the value for mw_model_warehouse.STATUS
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.STATUS:Coloured
     *
     * @param statusColoured the value for mw_model_warehouse.STATUS:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.LAST_UPDATE_TIME
     *
     * @return the value of mw_model_warehouse.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of mw_model_warehouse.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of mw_model_warehouse.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isLastUpdateTimeNotColoured() {
        return !lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for mw_model_warehouse.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for mw_model_warehouse.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.LAST_UPDATE_OPER
     *
     * @return the value of mw_model_warehouse.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of mw_model_warehouse.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of mw_model_warehouse.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isLastUpdateOperNotColoured() {
        return !lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for mw_model_warehouse.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for mw_model_warehouse.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.CREATE_TIME
     *
     * @return the value of mw_model_warehouse.CREATE_TIME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.CREATE_TIME:Coloured
     *
     * @return the value of mw_model_warehouse.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.CREATE_TIME:Coloured
     *
     * @return the value of mw_model_warehouse.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isCreateTimeNotColoured() {
        return !createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.CREATE_TIME
     *
     * @param createTime the value for mw_model_warehouse.CREATE_TIME
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for mw_model_warehouse.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.CREATE_OPER
     *
     * @return the value of mw_model_warehouse.CREATE_OPER
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.CREATE_OPER:Coloured
     *
     * @return the value of mw_model_warehouse.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mw_model_warehouse.CREATE_OPER:Coloured
     *
     * @return the value of mw_model_warehouse.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public boolean isCreateOperNotColoured() {
        return !createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.CREATE_OPER
     *
     * @param createOper the value for mw_model_warehouse.CREATE_OPER
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mw_model_warehouse.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for mw_model_warehouse.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mw_model_warehouse
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if(!(that instanceof MwModelWarehouse)) {
            return false;
        }
        MwModelWarehouse other = (MwModelWarehouse) that;
        return (this.getMwId() == null ? other.getMwId() == null : this.getMwId().equals(other.getMwId()))
            && (this.getMwCode() == null ? other.getMwCode() == null : this.getMwCode().equals(other.getMwCode()))
            && (this.getMwName() == null ? other.getMwName() == null : this.getMwName().equals(other.getMwName()))
            && (this.getMwType() == null ? other.getMwType() == null : this.getMwType().equals(other.getMwType()))
            && (this.getOwnerProjectId() == null ? other.getOwnerProjectId() == null : this.getOwnerProjectId().equals(other.getOwnerProjectId()))
            && (this.getModelDfsDir() == null ? other.getModelDfsDir() == null : this.getModelDfsDir().equals(other.getModelDfsDir()))
            && (this.getModelLocalDir() == null ? other.getModelLocalDir() == null : this.getModelLocalDir().equals(other.getModelLocalDir()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mw_model_warehouse
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMwId() == null) ? 0 : getMwId().hashCode());
        result = prime * result + ((getMwCode() == null) ? 0 : getMwCode().hashCode());
        result = prime * result + ((getMwName() == null) ? 0 : getMwName().hashCode());
        result = prime * result + ((getMwType() == null) ? 0 : getMwType().hashCode());
        result = prime * result + ((getOwnerProjectId() == null) ? 0 : getOwnerProjectId().hashCode());
        result = prime * result + ((getModelDfsDir() == null) ? 0 : getModelDfsDir().hashCode());
        result = prime * result + ((getModelLocalDir() == null) ? 0 : getModelLocalDir().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mw_model_warehouse
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    public void copyProperties(MwModelWarehouse that) {
        if (this == that || that == null) {
            return;
        }
        if(that.isMwIdColoured() ) {this.setMwId(that.getMwId() );}
        if(that.isMwCodeColoured() ) {this.setMwCode(that.getMwCode() );}
        if(that.isMwNameColoured() ) {this.setMwName(that.getMwName() );}
        if(that.isMwTypeColoured() ) {this.setMwType(that.getMwType() );}
        if(that.isOwnerProjectIdColoured() ) {this.setOwnerProjectId(that.getOwnerProjectId() );}
        if(that.isModelDfsDirColoured() ) {this.setModelDfsDir(that.getModelDfsDir() );}
        if(that.isModelLocalDirColoured() ) {this.setModelLocalDir(that.getModelLocalDir() );}
        if(that.isDescriptionColoured() ) {this.setDescription(that.getDescription() );}
        if(that.isStatusColoured() ) {this.setStatus(that.getStatus() );}
        if(that.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(that.getLastUpdateTime() );}
        if(that.isLastUpdateOperColoured() ) {this.setLastUpdateOper(that.getLastUpdateOper() );}
        if(that.isCreateTimeColoured() ) {this.setCreateTime(that.getCreateTime() );}
        if(that.isCreateOperColoured() ) {this.setCreateOper(that.getCreateOper() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mw_model_warehouse
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    @Override
    public JSONObject toJSON() {
        JSONObject jsonObj = new JSONObject(32, true);
        if(this.mwId != null) {jsonObj.put("mwId", this.mwId);}
        if(this.mwCode != null) {jsonObj.put("mwCode", this.mwCode);}
        if(this.mwName != null) {jsonObj.put("mwName", this.mwName);}
        if(this.mwType != null) {jsonObj.put("mwType", this.mwType);}
        if(this.ownerProjectId != null) {jsonObj.put("ownerProjectId", this.ownerProjectId);}
        if(this.modelDfsDir != null) {jsonObj.put("modelDfsDir", this.modelDfsDir);}
        if(this.modelLocalDir != null) {jsonObj.put("modelLocalDir", this.modelLocalDir);}
        if(this.description != null) {jsonObj.put("description", this.description);}
        if(this.status != null) {jsonObj.put("status", this.status);}
        if(this.lastUpdateTime != null) {jsonObj.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOper != null) {jsonObj.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTime != null) {jsonObj.put("createTime", this.createTime);}
        if(this.createOper != null) {jsonObj.put("createOper", this.createOper);}
        return jsonObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mw_model_warehouse
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    @Override
    public void clear() {
         this.mwId = null; this.mwIdColoured = false;
         this.mwCode = null; this.mwCodeColoured = false;
         this.mwName = null; this.mwNameColoured = false;
         this.mwType = null; this.mwTypeColoured = false;
         this.ownerProjectId = null; this.ownerProjectIdColoured = false;
         this.modelDfsDir = null; this.modelDfsDirColoured = false;
         this.modelLocalDir = null; this.modelLocalDirColoured = false;
         this.description = null; this.descriptionColoured = false;
         this.status = null; this.statusColoured = false;
         this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;
         this.lastUpdateOper = null; this.lastUpdateOperColoured = false;
         this.createTime = null; this.createTimeColoured = false;
         this.createOper = null; this.createOperColoured = false;
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mw_model_warehouse
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    @Override
    public void clearColoured() {
        this.mwIdColoured = false;
        this.mwCodeColoured = false;
        this.mwNameColoured = false;
        this.mwTypeColoured = false;
        this.ownerProjectIdColoured = false;
        this.modelDfsDirColoured = false;
        this.modelLocalDirColoured = false;
        this.descriptionColoured = false;
        this.statusColoured = false;
        this.lastUpdateTimeColoured = false;
        this.lastUpdateOperColoured = false;
        this.createTimeColoured = false;
        this.createOperColoured = false;
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mw_model_warehouse
     *
     * @mbg.generated Fri Jan 25 00:48:21 CST 2019
     */
    @Override
    public boolean isColoured() {
        if(this.mwIdColoured) return true;
        if(this.mwCodeColoured) return true;
        if(this.mwNameColoured) return true;
        if(this.mwTypeColoured) return true;
        if(this.ownerProjectIdColoured) return true;
        if(this.modelDfsDirColoured) return true;
        if(this.modelLocalDirColoured) return true;
        if(this.descriptionColoured) return true;
        if(this.statusColoured) return true;
        if(this.lastUpdateTimeColoured) return true;
        if(this.lastUpdateOperColoured) return true;
        if(this.createTimeColoured) return true;
        if(this.createOperColoured) return true;
        return false;
    }
}